version: "3.3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_DOT_ENV: $SECRET_DOT_ENV
    container_name: secret-test
    env_file:
      - .env_file